using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Application.Common;

public class SharedResources
{
    public const string FileStreamRequired = "FileStreamRequired";
    public const string FileNameRequired = "FileNameRequired";
    public const string InvalidExtensionError = "InvalidExtensionError";
    public const string BucketNotFound = "BucketNotFound";
    public const string ConfigurationRequired = "ConfigurationRequired";
    public const string LoggerRequired = "LoggerRequired";
    public const string LocalizerRequired = "LocalizerRequired";
    public const string SupabaseUrlRequired = "SupabaseUrlRequired";
    public const string SupabasePublicKeyRequired = "SupabasePublicKeyRequired";
    public const string SupabaseSecretKeyRequired = "SupabaseSecretKeyRequired";
    public const string SupabaseBucketNameRequired = "SupabaseBucketNameRequired";
    public const string SupabasePublicUrlRequired = "SupabasePublicUrlRequired";
    public const string BookIdRequired = "BookIdRequired";
    public const string UserNotFound = "UserNotFound";
    public const string BookNotFound = "BookNotFound";
    public const string TagNotFound = "TagNotFound";
    public const string UserBlocked = "UserBlocked";
    public const string InvalidPassword = "InvalidPassword";
    public const string UnauthorizedAccess = "UnauthorizedAccess";
    public const string AdminOnlyAccess = "AdminOnlyAccess";
    public const string EmptyString = "EmptyString";
    public const string MaxLength = "MaxLength";
    public const string EmailRequired = "EmailRequired";
    public const string InvalidEmailFormat = "InvalidEmailFormat";
    public const string EmailTooLong = "EmailTooLong";
    public const string PasswordRequired = "PasswordRequired";
    public const string PasswordTooShort = "PasswordTooShort";
    public const string PasswordRequiresUppercase = "PasswordRequiresUppercase";
    public const string PasswordRequiresNumber = "PasswordRequiresNumber";
    public const string UsernameRequired = "UsernameRequired";
    public const string UsernameTooLong = "UsernameTooLong";
    public const string InvalidUsernameFormat = "InvalidUsernameFormat";
    public const string UserIdRequired = "UserIdRequired";
    public const string BookDataRequired = "BookDataRequired";
    public const string TitleRequired = "TitleRequired";
    public const string TitleTooLong = "TitleTooLong";
    public const string AuthorRequired = "AuthorRequired";
    public const string AuthorTooLong = "AuthorTooLong";
    public const string DescriptionTooLong = "DescriptionTooLong";
    public const string TagsRequired = "TagsRequired";
    public const string InvalidTagIds = "InvalidTagIds";
    public const string FilterRequired = "FilterRequired";
    public const string InvalidPageNumber = "InvalidPageNumber";
    public const string InvalidPageSize = "InvalidPageSize";
    public const string SearchQueryTooLong = "SearchQueryTooLong";
    public const string InvalidSortBy = "InvalidSortBy";
    public const string AtLeastOneFieldRequired = "AtLeastOneFieldRequired";
    public const string CoverImageUrlRequired = "CoverImageUrlRequired";
    public const string CoverImageUrlTooLong = "CoverImageUrlTooLong";
    public const string InvalidCoverImageUrl = "InvalidCoverImageUrl";
    public const string TagNameRequired = "TagNameRequired";
    public const string TagNameTooLong = "TagNameTooLong";
    public const string InvalidTagNameFormat = "InvalidTagNameFormat";
    public const string AdminIdRequired = "AdminIdRequired";
    public const string RoleRequired = "RoleRequired";
    public const string InvalidRole = "InvalidRole";
    public const string RefreshTokenRequired = "RefreshTokenRequired";
    public const string RefreshTokenTooLong = "RefreshTokenTooLong";
}
